### ISSUE TITLE
AES-GCM

### ISSUE THREAD

**Issue by badbrain79** [ministryofjay/ipsec-overhead-calculator#1]
If I select ESP-GCM as encryption, ESP ICV should be replaced by the GCM tag, as AES-GCM does not require an ICV and is replaced by the GCM tag.

**Comment by ministryofjay-cisco** [comment]
@badbrain79, Thanks for the feedback.  In reading https://www.rfc-editor.org/rfc/rfc4106.html#section-6 it is my understanding that the ESP ICV is set to the output of the GCM encryption operation (AES-GCM Authentication Tag) so the size and location remains the same. https://datatracker.ietf.org/doc/html/rfc4303#section-2.8

Are you suggesting that the ESP ICV should be re-named to "AES authentication tag" when ESP-GCM is selected?

**Comment by badbrain79** [comment]
RFC 5116 refers to the authentication tag in AES-GCM and is therefore often abbreviated as GCM tag. But it's not really that important, it's just a name. The main thing is that the length is correct.
